### ISSUE TITLE
:green_heart: Let's move from Travis to GitHubAction.

### ISSUE THREAD

**Issue by tkoyama010** [python/python-docs-ja#26]
Hi all. How about moving CI from Travis to GitHubActions? Let me know what you think.

**Comment by tkoyama010** [comment]
FYI this repository is good. [This](https://github.com/getfem-doc/mayavi-doc-translations/blob/master/.github/workflows/main.yml) yml may be helpful.

**Comment by cocoatomo** [comment]
Requirements of CI build is described in the wiki [page](https://github.com/python-doc-ja/python-doc-ja/wiki/TranslationWorkflow).
Besides, I have a plan of PR build to display documentation built from source files that PR merged.

Please help me with an assessment.

## GitHub Action
### Pros.
- Easily recognize types of event
- Many GitHub Actions already exist are available
- automatic GITHUB_TOKEN creation and expiration
- ?
### Cons.
-  It turns out that each step in a job is executed in a sort-of separate environment, and one step is unable to export environment variables that another step could read.
  - ref. https://bravelab.io/blog/migrating-from-travisci-to-github-actions-1/
- An environment variable is hard to store an SSH key file.
- ?
### Unknown.
- Can GitHub Action fully satisfy the requirements above?
- Is storing secrets easier than Travis ci?
- Can access across repositories easier? 
- ?

**Comment by cocoatomo** [comment]
The feature of automatic `GITHUB_TOKEN` creation is very helpful to push the results of PR builds. Moreover, the tokens have existence time limits, 60 minutes.

**Comment by cocoatomo** [comment]
Two workflows, [pr_build.yml](https://github.com/python/python-docs-ja/blob/ae48c93e52c7a5dc5b68c403f15fb583d343c241/.github/workflows/pr_build.yml) and [delete_pr_built_doc.yml](https://github.com/python/python-docs-ja/blob/ae48c93e52c7a5dc5b68c403f15fb583d343c241/.github/workflows/delete_pr_built_doc.yml), are now working!

**Comment by rffontenelle** [comment]
Hi there. I landed in here while checking the Travis solution. Is Travis run manually or scheduled ? I see that [all branches' last build](https://app.travis-ci.com/github/python/python-docs-ja/branches) happened 4 months ago, hence some fixes to the docs are not available in Transifex for translation.

In the spirit of the pros and cons, GitHub Actions features `on.schedule` events that are cron-like syntaxes, allowing to run the workflow daily.

**Comment by rffontenelle** [comment]
GitHub Actions are now in use. Should this be closed?

**Comment by tkoyama010** [comment]
Yes. Thanks.
